### ISSUE TITLE
ebirdhistorical error for loc = "AR"

### ISSUE THREAD

**Issue by peetmate** [ropensci/rebird#81] opened 2020-05-31 09:18 UTC
Hello,

I am trying to download data for Argentina using the ebirdhistorical function:

`ebirdhistorical(loc="AR",date="2020-05-09",key = EBIRD_KEY)`

This gives the error:
`Error in ebird_GET(url, args, key = key, ...) :   500 -- http.status.500 -- PreparedStatementCallback; SQL  ORA-01013: user requested cancel of current operation; nested exception is java.sql.SQLTimeoutException: ORA-01013: user requested cancel of current operation`

I have also tried:
`ebirdhistorical(loc="AR",date="2020-05-09",key = BIRD_KEY, config= httr::timeout(60*10)), max=10000)`
I get the same error.

The function works for other regions (including US, CO & KE) just fine, but not AR. What could the issue be?
Date of my download attempt = "2020-05-31"

Many thanks,

Pete S

**Comment by peetmate** [comment] 2020-05-31 09:46
Also get the same error for "PA" every other country is fine

**Comment by ateucher** [comment] 2020-06-01 19:38
This is strange, and I can reproduce it outside of R, using `curl` in the terminal: 

```
curl -k --location --request GET "https://api.ebird.org/v2/data/obs/AR/historic/2020/05/09" --header 'X-eBirdApiToken: {my-api-key}'
```

However it works for other dates for `AR` (in R as well as on the command line):

``` r
library(rebird)
ebirdhistorical(loc="AR", date="2020-05-10", max = 10)
#> # A tibble: 10 x 13
#>    speciesCode comName sciName locId locName obsDt howMany   lat   lng obsValid
#>    <chr>       <chr>   <chr>   <chr> <chr>   <chr>   <int> <dbl> <dbl> <lgl>   
#>  1 brnowl      Barn O… Tyto a… L112… Calle … 2020…       1 -33.0 -60.8 TRUE    
#>  2 puteup1     Purple… Euphon… L114… 1690 C… 2020…       1 -27.4 -55.9 TRUE    
#>  3 banana      Banana… Coereb… L114… 1690 C… 2020…       1 -27.4 -55.9 TRUE    
#>  4 spwpig3     Spot-w… Patagi… L112… 6500 B… 2020…      NA -31.5 -64.2 TRUE    
#>  5 eardov1     Eared … Zenaid… L112… 6500 B… 2020…      NA -31.5 -64.2 TRUE    
#>  6 soulap1     Southe… Vanell… L112… 6500 B… 2020…      NA -31.5 -64.2 TRUE    
#>  7 burowl      Burrow… Athene… L112… 6500 B… 2020…      NA -31.5 -64.2 TRUE    
#>  8 soucar1     Southe… Caraca… L112… 6500 B… 2020…      NA -31.5 -64.2 TRUE    
#>  9 chicar1     Chiman… Milvag… L112… 6500 B… 2020…      NA -31.5 -64.2 TRUE    
#> 10 monpar      Monk P… Myiops… L112… 6500 B… 2020…      NA -31.5 -64.2 TRUE    
#> # … with 3 more variables: obsReviewed <lgl>, locationPrivate <lgl>,
#> #   subId <chr>
```

May 9 was the global big day... I wonder if that has anything to do with it?

**Comment by ateucher** [comment] 2020-06-01 19:52
@sebpardo I couldn't find a direct way to report api bugs... do you have a contact?

**Comment by ateucher** [comment] 2020-06-03 16:39
FYI I've submitted a ticket to eBird support... will let you know what they say

**Comment by sebpardo** [comment] 2020-07-14 21:09
> @sebpardo I couldn't find a direct way to report api bugs... do you have a contact?
Apologies for the very late reply. The person to contact on eBird Central is Tim Lenz, if you haven't already gotten a reply from him I can email him directly.

**Comment by ateucher** [comment] 2020-07-14 21:12
Hi @sebpardo I did submit a ticket to https://support.ebird.org/en/support/home about a month ago, haven't heard anything (nor have I tested it again). I did hear that the API team was pretty swamped...

**Comment by sebpardo** [comment] 2020-07-29 15:15
Hi @peetmate and @ateucher, would you mind trying this again to see if the error persists? I think this might have been fixed by eBird Central as I can't reproduce the error when using `rebird` or the console when using `curl`.

**Comment by ateucher** [comment] 2020-08-10 23:03
It's working for me now too, I think we can close it!

**Closed by ateucher** 2020-08-10 23:03 UTC
