### ISSUE TITLE
Push v0.2 to CRAN soon?

### ISSUE THREAD

**Issue by sckott** [ropensci/rebird#7] opened 2013-11-30 00:27 UTC
Seems like we've had many changes in this package lately. Should we push a new version `v0.2` to CRAN soon?  

I made a milestone for this `v0.2` we can assign issues to.

**Comment by sckott** [comment] 2015-05-14 14:52
@rmaia can we push a new version to cran soon?  `0.2` seems appropriate

**Comment by sebpardo** [comment] 2015-05-28 05:17
@sckott would it be a good idea to email @rmaia?

**Comment by rmaia** [comment] 2015-05-28 06:05
sorry for the delay. I'll try to get it done by the end of the week.

**Comment by sckott** [comment] 2015-05-28 14:49
@rmaia Thanks!

**Comment by sckott** [comment] 2015-06-26 22:17
@rmaia do you'll think you'll get a chance to submit to CRAN soon?

**Comment by sebpardo** [comment] 2015-06-27 23:07
@rmaia if you want to pass on being the maintainer I would gladly take on the responsibility, unless @ateucher or @sckott want to do it themselves.

**Comment by rmaia** [comment] 2015-06-30 13:05
sorry - been moving and my life is pretty upside down. @sebpardo, perhaps that's a good idea. you guys have been more on top of things and I probably wouldn't even know how to correct any issues that arise during submission to CRAN. Whomever you guys decide is best for the job, I'm fine with it!

**Comment by sckott** [comment] 2015-06-30 16:36
Thanks @rmaia ! You'll of course still be an author

@sebpardo Please do takeover, if that's okay @ateucher ?  When you submit to CRAN you'll need written permission from @rmaia that you are taking over. relevant line from CRAN policies

> When a new maintainer wishes to take over a package, this should be accompanied by the written agreement of the previous maintainer (unless the package has been formally orphaned).

**Comment by sebpardo** [comment] 2015-06-30 22:38
@rmaia is there any submission comments from the last CRAN push that we should be aware of?

**Comment by rmaia** [comment] 2015-06-30 22:40
nope!

let me know how or where I should include the written agreement.

**Comment by rmaia** [comment] 2015-07-01 00:13
the winbuilder notice still came to my email:

>Dear package maintainer,
this notification has been generated automatically.
Your package rebird_0.1.6.9000.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
http://win-builder.r-project.org/L5He3jh2Il7M
The files will be removed after roughly 72 hours.
Installation time in seconds: 4
Check time in seconds: 54
Check result: OK
R Under development (unstable) (2015-06-29 r68604)
All the best,
Uwe Ligges
(CRAN maintainer of binary packages for Windows)

**Comment by sebpardo** [comment] 2015-07-01 00:18
@rmaia yep, sorry about that. Was running `devtools::build_win()` before changing the maintainer in the DESCRIPTION. Now it's fixed in my fork so you won't get those anymore.

**Comment by rmaia** [comment] 2015-07-01 00:22
just in case you need the info, I got another one :)

>Dear package maintainer,
this notification has been generated automatically.
Your package rebird_0.1.6.9000.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
http://win-builder.r-project.org/d5Ky65Bv4ZCu
The files will be removed after roughly 72 hours.
Installation time in seconds: 4
Check time in seconds: 56
Check result: OK
R version 3.2.1 (2015-06-18)
All the best,
Uwe Ligges
(CRAN maintainer of binary packages for Windows)

**Comment by sebpardo** [comment] 2015-07-01 00:47
Hahaha sorry again, the second one is done on the stable version of R instead of the Development one, hence the two emails. Wasn't counting on that!

**Comment by sebpardo** [comment] 2015-07-02 21:33
Hey @sckott I have everything pretty much ready to go but I'll wait for @ateucher to reply before I go ahead.

**Comment by sckott** [comment] 2015-07-02 21:40
@sebpardo I'll see if I can get him on twitter DM

**Comment by sckott** [comment] 2015-07-02 22:23
@sebpardo  let's go ahead with the submission

**Comment by sebpardo** [comment] 2015-07-02 22:27
Ok, should version be 0.2, 0.2.0, or 0.2.0.0?

**Comment by sckott** [comment] 2015-07-02 22:37
@sebpardo if you could, please:

* note that next version should be `v0.2` and linked to changes under milestone  https://github.com/ropensci/rebird/milestones/v0.2 - remember to close that milestone when submission done and on CRAN
* git tag the final commit that goes to CRAN
* and put relevant NEWS items in a release with that tag at https://github.com/ropensci/rebird/releases

**Comment by sebpardo** [comment] 2015-07-02 23:19
@sckott this is probably a silly question, but what should I write in the "Optional comments" field when submitting? What's on cran-comments, NEWS, or both?

**Comment by sckott** [comment] 2015-07-02 23:27
Are you using `devtools::release()` ?

**Comment by sckott** [comment] 2015-07-02 23:28
See eg of `cran-comments.md` https://github.com/hadley/httr/blob/master/cran-comments.md

Eg. of `NEWS` https://github.com/hadley/httr/blob/master/NEWS.md

**Comment by sebpardo** [comment] 2015-07-02 23:35
Sorry, that question didn't read very well. I've created `cran-comments.md` and `NEWS.md` according to Hadley's suggestions, however I'm not sure if I should paste the contents of either (or both) on  "Optional comments" field when submitting to CRAN.

I am not using `devtools::release()` as I get an error; the updated release is in the process of being submitted to CRAN (see https://github.com/hadley/devtools/issues/858)

**Comment by sckott** [comment] 2015-07-02 23:40
Okay. I haven't used that submission form in a long time, but I think you want cran-comments stuff  in the "Optional comments" box. NEWS items are included in the package `tar.gz` that you upload

**Comment by sebpardo** [comment] 2015-07-02 23:41
Perfect! I am going to submit now and link to this thread with regards to the maintainer change and written consent.

**Comment by sebpardo** [comment] 2015-07-02 23:46
Submitted.

**Comment by ateucher** [comment] 2015-07-03 18:37
Nice work all!

**Comment by sckott** [comment] 2015-07-07 19:07
@sebpardo Hows it going with the submission to cran?  I assume it got bounced back.  need any help?

**Comment by sebpardo** [comment] 2015-07-07 20:56
@sckott I hadn't received any emails from CRAN yet so I double checked, and it happens I hadn't confirmed my submission...

It's uploaded to CRAN now :)

**Comment by sckott** [comment] 2015-07-07 20:56
Oh good!

**Comment by sebpardo** [comment] 2015-07-08 18:43
I got a reply from Uwe:

>New maintainer:
>  Sebastian Pardo <sebpardo@gmail.com>
>Old maintainer(s):
>  Rafael Maia <rm72@zips.uakron.edu>
>
>Have we got confirmation from the old maintainer already?


@rmaia, could you please email CRAN <cran@r-project.org> and let them know directly?

>* checking R code for possible problems ... NOTE
>ebird_GET : <anonymous> : <anonymous>: no visible global function
>  definition for 'is'
>ebirdfreq: no visible global function definition for 'read.delim'
>ebirdfreq: no visible global function definition for 'reshape'
>Undefined global functions or variables:
>  is read.delim reshape
>
>Please import these (ideally selectively) from the default packages other than "base" (see ?R_DEFAULT_PACKAGES).

This last NOTE only popped up on the devel version of R when running `devtools::build_win()`. Functions `is`, `read.delim`, and `reshape` are included in the utils and `stats packages in base R. Is it perhaps something that is changing in future versions? To import selectively do we use `importFrom` in roxygen2?

Also, do I reply directly yo Uwe or do I begin a completely new CRAN submission?

Almost there!

**Comment by ateucher** [comment] 2015-07-08 18:59
I saw something recently that only `base` functions are available without importing - so I think your solution to use `importFrom` from those packages is probably a good way to go. (Or would using `stats::reshape` etc suffice?)

**Comment by ateucher** [comment] 2015-07-08 19:20
That looks like it's how @sckott did it in `spocc`: https://github.com/ropensci/spoccutils/commit/178fc26394e208358b68989e733e6852e2e8bb03

**Comment by sckott** [comment] 2015-07-08 19:27
Yes, you now need to import all functions that are not in the base R pkg, so anything from utils, stats, methods, etc. packages that are come with R, and are loaded by default, but now they want you to specify which functions in those packages you are using in your package. 

I usually do this in the package level man file like https://github.com/ropensci/spoccutils/blob/master/R/spoccutils-package.R#L3-L6

**Comment by sckott** [comment] 2015-07-08 19:27
You can reply to him saying you'll fix that stuff, but you need to do a new submission, with same version number

**Comment by sebpardo** [comment] 2015-07-08 21:42
Thanks @ateucher and @sckott! Scott, can I get away with just specifying the functions using `@importFrom` in the package level man file and not in the DESCRIPTION file?

**Comment by sebpardo** [comment] 2015-07-08 22:39
Re-submitted to CRAN. @rmaia has notified them of the change, I've PR the latest changes and updated the release. Should be good!

**Comment by sckott** [comment] 2015-07-08 22:50
@sebpardo looks like you got it already, but to answer your question: yes, you need to have methods, utils, stats, etc. pkgs listed in DESCRIPTION file as well

**Comment by sebpardo** [comment] 2015-07-09 15:31
rebird v0.2 is on CRAN.

**Comment by sckott** [comment] 2015-07-09 15:31
:+1:

**Closed by sebpardo** 2015-07-09 15:31 UTC
